### ISSUE TITLE
Git submodule 403 failure

### ISSUE THREAD

**Issue by sitsang** [Fat-Zer/trinity#3]
> > > Emerging (2 of 3) dev-libs/dbus-1-tqt-9999::trinity
> > > Unpacking source...
> > > Cloning into '/usr/portage/distfiles/egit-src/trinity/dbus-1-tqt'...
> > > Checking connectivity... done.
> > > GIT NEW clone -->
> > >    repository:               http://mirror.git.trinitydesktop.org/cgit/dbus-1-tqt
> > >    at the commit:            f853b90d63328cdc5732c489ce19e69b7b60e326
> > >    branch:                   master
> > >    storage directory:        "/usr/portage/distfiles/egit-src/trinity/dbus-1-tqt"
> > >    checkout type:            non-bare repository
> > > Submodule 'admin' (http://system@scm.trinitydesktop.org/scm/git/tde-common-admin) registered for path 'admin'
> > > Submodule 'cmake' (http://system@scm.trinitydesktop.org/scm/git/tde-common-cmake) registered for path 'cmake'
> > > Synchronizing submodule url for 'admin'
> > > Synchronizing submodule url for 'cmake'
> > > Cloning into 'admin'...
> > > fatal: unable to access 'http://system@scm.trinitydesktop.org/scm/git/tde-common-admin/': The requested URL returned error: 403
> > > Clone of 'http://system@scm.trinitydesktop.org/scm/git/tde-common-admin' into submodule path 'admin' failed
> > > - ERROR: dev-libs/dbus-1-tqt-9999::trinity failed (unpack phase):
> > > -   (no error message)

**Comment by Fat-Zer** [comment]
The upstream mirror was down for some time today... can you check again?
Also note that I will likely migrate to git-r3 eclass soon and you will likely have to refetch the sources...

**Comment by Fat-Zer** [comment]
Also note that if you set TRINITY_GIT_MIRROR the submodules will be downloaded from the main mirror anyway. I don't know a way to bypass it...

**Comment by sitsang** [comment]
You can change the eclass to do Git Pull from http://mirror.git.trinitydesktop.org/cgit/{...}.  The problem is that the Gentoo's ebuild will see the .gitmodules file, which is still pointing to scm.trinitydesktop.org/scm/git/tde-common-admin instead of the mirror.  We could certainly work around this be doing a sed on the .gitmodules ourselves, but to do so requires rewriting the git eclass.

I don't foresee migrating to git-r3 eclass would fix this issue.

**Comment by Fat-Zer** [comment]
> The problem is that the Gentoo's ebuild will see the .gitmodules file, which is still pointing to scm.trinitydesktop.org/scm/git/tde-common-admin instead of the mirror.

Yes, it's a general draw back of using submodules: there is no sane way to tell to git that they were mirrored... But cmake and admin are relatively small so this is IMHO not a big deal that they are getting updated from the slower mirror...
The most that should be done is a line to be dropped into TRINITY_GIT_MIRROR description about that or it may be consider as a strictly internal variable...

> We could certainly work around this be doing a sed on the .gitmodules ourselves, but to do so requires rewriting the git eclass.

Firstly, I don't want to alter and maintain a copy of a git eclass here.
Secondly, I'm not yet sure that this will workout just that easy anyway...

> I don't foresee migrating to git-r3 eclass would fix this issue.

I suppose you are right, moreover due to they removed EGIT_PROJECT there will be not possible to alter mirrors at all and if kde guys will migrate too this will likely result in conflicts, so I'm still not sure that I will finally do this...

**Comment by Fat-Zer** [comment]
The bug is treversome outdated... cloasing...

PS: The overlay is officially dead now. Please checkout the version maintained by trinity desktop environment community: https://mirror.git.trinitydesktop.org/gitea/TDE/tde-packaging-gentoo
